const db = require('../../server/db')
const {User} = require('../../server/db/models')
const usersData = [
  {
    email: 'tsimioli0@drupal.org',
    password: 'mPJtQQQR2hXB',
    googleId: '9465857068',
    firstName: 'Theodosia',
    lastName: 'Simioli',
    phone: '917-824-7280',
  },
  {
    email: 'umccotter1@theguardian.com',
    password: 'WKouzgkgSr',
    googleId: '0254601839',
    firstName: 'Umeko',
    lastName: 'McCotter',
    phone: null,
  },
  {
    email: 'rcolegate2@uol.com.br',
    password: 'tk8TUFeeJ',
    googleId: '9543355932',
    firstName: 'Rosabelle',
    lastName: 'Colegate',
    phone: null,
  },
  {
    email: 'mpaternoster3@patch.com',
    password: '4CpfqeJ2',
    googleId: '4416093306',
    firstName: 'Melina',
    lastName: 'Paternoster',
    phone: null,
  },
  {
    email: 'sdight4@delicious.com',
    password: 'wXbfQ35NS',
    googleId: '3609516763',
    firstName: 'Sansone',
    lastName: 'Dight',
    phone: '459-462-0044',
  },
  {
    email: 'emacmychem5@creativecommons.org',
    password: 'pP8Rm5kAAtPY',
    googleId: '6445323340',
    firstName: 'Essie',
    lastName: 'MacMychem',
    phone: '256-435-9557',
  },
  {
    email: 'csebire6@prnewswire.com',
    password: 'GVSql22iHDKW',
    googleId: '7092143535',
    firstName: 'Cooper',
    lastName: 'Sebire',
    phone: null,
  },
  {
    email: 'ldungey7@goodreads.com',
    password: 'KdtXp2',
    googleId: '5641494291',
    firstName: 'Lodovico',
    lastName: 'Dungey',
    phone: null,
  },
  {
    email: 'gwainer8@blogs.com',
    password: 'fRnfoMA32rN',
    googleId: '5471487052',
    firstName: 'Gannon',
    lastName: 'Wainer',
    phone: '763-528-7659',
  },
  {
    email: 'awycherley9@pinterest.com',
    password: '3ru7kLrvtFDb',
    googleId: '9636279683',
    firstName: 'Annette',
    lastName: 'Wycherley',
    phone: null,
  },
  {
    email: 'tfessbya@mail.ru',
    password: 'lsGoyc5mZ',
    googleId: '9466262831',
    firstName: 'Tab',
    lastName: 'Fessby',
    phone: '712-578-3947',
  },
  {
    email: 'rcastagnob@geocities.com',
    password: 'EMUw8faZVI',
    googleId: '1540979563',
    firstName: 'Rhianna',
    lastName: 'Castagno',
    phone: '740-752-0355',
  },
  {
    email: 'rguerrieric@apache.org',
    password: 'DqiNpf',
    googleId: '2826336800',
    firstName: 'Roz',
    lastName: 'Guerrieri',
    phone: '323-651-4501',
  },
  {
    email: 'mdoersd@artisteer.com',
    password: '3OSulz0vJgTv',
    googleId: '5026733239',
    firstName: 'Melisa',
    lastName: 'Doers',
    phone: '640-701-6914',
  },
  {
    email: 'colmane@mashable.com',
    password: 'UlGk1TJkd2',
    googleId: '5214713665',
    firstName: 'Candy',
    lastName: 'Olman',
    phone: '785-232-9567',
  },
  {
    email: 'pcaramusciaf@homestead.com',
    password: '7TdbonHIqK1',
    googleId: '1945708980',
    firstName: 'Pyotr',
    lastName: 'Caramuscia',
    phone: '485-745-9263',
  },
  {
    email: 'ndarrigoneg@nasa.gov',
    password: 'X1XHpV',
    googleId: '9412248911',
    firstName: 'Neda',
    lastName: 'Darrigone',
    phone: '223-592-5371',
  },
  {
    email: 'dmeinerh@odnoklassniki.ru',
    password: '7KXb3gIP',
    googleId: '8698703097',
    firstName: 'Dirk',
    lastName: 'Meiner',
    phone: null,
  },
  {
    email: 'hlockyeari@amazonaws.com',
    password: 'YWGjusKSG',
    googleId: '7984144346',
    firstName: 'Hashim',
    lastName: 'Lockyear',
    phone: '431-235-9480',
  },
  {
    email: 'shumanj@nature.com',
    password: 'LkRYsuMut1Vj',
    googleId: '1797784544',
    firstName: 'Sheff',
    lastName: 'Human',
    phone: null,
  },
  {
    email: 'smoyserk@hp.com',
    password: 'nYVGWXXcpT8i',
    googleId: '6907793334',
    firstName: 'Scarlet',
    lastName: 'Moyser',
    phone: null,
  },
  {
    email: 'apeppettl@gizmodo.com',
    password: 'uI44IN4MeB',
    googleId: '6419066727',
    firstName: 'Alexio',
    lastName: 'Peppett',
    phone: '835-726-4757',
  },
  {
    email: 'beathornem@umn.edu',
    password: 'TucRtwTv0C',
    googleId: '7941016281',
    firstName: 'Berthe',
    lastName: 'Eathorne',
    phone: null,
  },
  {
    email: 'rmacanellyen@is.gd',
    password: 'gPllVHPwL',
    googleId: '1236144392',
    firstName: 'Randee',
    lastName: 'MacAnellye',
    phone: null,
  },
  {
    email: 'kploseo@telegraph.co.uk',
    password: 'jxxlpsm2i',
    googleId: '5198463922',
    firstName: 'Kate',
    lastName: 'Plose',
    phone: '683-137-0581',
  },
  {
    email: 'jgouldthorpep@skyrock.com',
    password: 'a5ZDAdPg8p',
    googleId: '2768783315',
    firstName: 'Janka',
    lastName: 'Gouldthorpe',
    phone: null,
  },
  {
    email: 'rroganq@google.it',
    password: 'wrKvibKpEEqa',
    googleId: '4188373121',
    firstName: 'Ruy',
    lastName: 'Rogan',
    phone: null,
  },
  {
    email: 'gmoter@bluehost.com',
    password: 'MlUjZ2if',
    googleId: '8490724164',
    firstName: 'Gaylene',
    lastName: 'Mote',
    phone: '609-634-5841',
  },
  {
    email: 'cmundwells@google.com.br',
    password: 'BjADdeYSCW',
    googleId: '0486196909',
    firstName: 'Cherye',
    lastName: 'Mundwell',
    phone: '134-858-4439',
  },
  {
    email: 'iakroydt@admin.ch',
    password: 'Cdgef5DDz',
    googleId: '3316308105',
    firstName: 'Isabel',
    lastName: 'Akroyd',
    phone: null,
  },
  {
    email: 'fwoodmanu@craigslist.org',
    password: 'dGggTsoHp7K4',
    googleId: '5463619336',
    firstName: 'Franny',
    lastName: 'Woodman',
    phone: '675-974-6110',
  },
  {
    email: 'dgritsunovv@livejournal.com',
    password: 'mip9vbk4c',
    googleId: '8274527259',
    firstName: 'Daryle',
    lastName: 'Gritsunov',
    phone: '151-325-7861',
  },
  {
    email: 'pswalloww@taobao.com',
    password: 'cOrqeBun0i',
    googleId: '3746991730',
    firstName: 'Powell',
    lastName: 'Swallow',
    phone: null,
  },
  {
    email: 'mkarlex@addthis.com',
    password: 'kfYdCpkwin3',
    googleId: '9830534472',
    firstName: 'Marielle',
    lastName: 'Karle',
    phone: '116-455-3784',
  },
  {
    email: 'tmurcotty@1und1.de',
    password: '9IR3bISIG',
    googleId: '2996464915',
    firstName: 'Tommy',
    lastName: 'Murcott',
    phone: '939-568-9044',
  },
  {
    email: 'dconradiez@github.com',
    password: 'Upj8XTG3lHDh',
    googleId: '9219163543',
    firstName: 'Desdemona',
    lastName: 'Conradie',
    phone: null,
  },
  {
    email: 'idyos10@mtv.com',
    password: 'dWcQUsrxn',
    googleId: '2198009145',
    firstName: 'Iona',
    lastName: 'Dyos',
    phone: null,
  },
  {
    email: 'wborley11@alexa.com',
    password: 'Vh8oljfGTyX3',
    googleId: '8744775830',
    firstName: 'Wallis',
    lastName: 'Borley',
    phone: '796-126-6851',
  },
  {
    email: 'bkorda12@deliciousdays.com',
    password: 'v8WRRtDL',
    googleId: '4791613260',
    firstName: 'Bryn',
    lastName: 'Korda',
    phone: '546-638-0074',
  },
  {
    email: 'lmitham13@salon.com',
    password: 'MlSCeb0b',
    googleId: '2086947518',
    firstName: 'Lena',
    lastName: 'Mitham',
    phone: '746-827-7972',
  },
  {
    email: 'lbedenham14@ibm.com',
    password: 'gJVm4N',
    googleId: '9742947597',
    firstName: 'Loree',
    lastName: 'Bedenham',
    phone: null,
  },
  {
    email: 'lconvery15@ft.com',
    password: 'B0G6GuP',
    googleId: '9077764666',
    firstName: 'Laney',
    lastName: 'Convery',
    phone: null,
  },
  {
    email: 'ablunsen16@yolasite.com',
    password: 'X9CvOnpaB',
    googleId: '6176506417',
    firstName: 'Allis',
    lastName: 'Blunsen',
    phone: null,
  },
  {
    email: 'vrubery17@google.com.hk',
    password: 'oIkuRJ',
    googleId: '2527079369',
    firstName: 'Vernice',
    lastName: 'Rubery',
    phone: null,
  },
  {
    email: 'mswatheridge18@vimeo.com',
    password: 'GWtmohr',
    googleId: '6472186456',
    firstName: 'Marillin',
    lastName: 'Swatheridge',
    phone: null,
  },
  {
    email: 'ngrane19@addtoany.com',
    password: 'N89Y66m',
    googleId: '9206350382',
    firstName: 'Nap',
    lastName: 'Grane',
    phone: null,
  },
  {
    email: 'eschulke1a@unblog.fr',
    password: 'IfbpFRR',
    googleId: '6319711787',
    firstName: 'Elisabet',
    lastName: 'Schulke',
    phone: '705-509-6537',
  },
  {
    email: 'cedes1b@google.com',
    password: '7RFgIz',
    googleId: '5370367701',
    firstName: 'Cory',
    lastName: 'Edes',
    phone: null,
  },
  {
    email: 'jgrishukov1c@cmu.edu',
    password: 'NWdhhBgs',
    googleId: '1889851213',
    firstName: 'Joel',
    lastName: 'Grishukov',
    phone: null,
  },
  {
    email: 'wfallens1d@shutterfly.com',
    password: '6Tyq56xTF20y',
    googleId: '4322556167',
    firstName: 'Willy',
    lastName: 'Fallens',
    phone: '461-797-2345',
  },
  {
    email: 'htewes1e@histats.com',
    password: 'w4PLtU4ll',
    googleId: '6567568917',
    firstName: 'Helen-elizabeth',
    lastName: 'Tewes',
    phone: null,
  },
  {
    email: 'tdominka1f@netvibes.com',
    password: 'cbwKEl',
    googleId: '4557920969',
    firstName: 'Tierney',
    lastName: 'Dominka',
    phone: null,
  },
  {
    email: 'sstaker1g@craigslist.org',
    password: 'FoRzKngJ',
    googleId: '2067014927',
    firstName: 'Sauncho',
    lastName: 'Staker',
    phone: null,
  },
  {
    email: 'hkleinmann1h@sun.com',
    password: 'XeGx1XYS',
    googleId: '4989385020',
    firstName: 'Helga',
    lastName: 'Kleinmann',
    phone: null,
  },
  {
    email: 'satwill1i@intel.com',
    password: 'yOXkzOWsaB',
    googleId: '6508666460',
    firstName: 'Sylvan',
    lastName: 'Atwill',
    phone: null,
  },
  {
    email: 'tboseley1j@infoseek.co.jp',
    password: 'bVeap0h2jV',
    googleId: '4125761124',
    firstName: 'Tine',
    lastName: 'Boseley',
    phone: '516-694-6731',
  },
  {
    email: 'aveighey1k@loc.gov',
    password: 'cp6dfxKqLMIL',
    googleId: '3154105484',
    firstName: 'Ag',
    lastName: 'Veighey',
    phone: null,
  },
  {
    email: 'kdewolfe1l@stumbleupon.com',
    password: 'RuwTRWF',
    googleId: '5687718338',
    firstName: 'Katheryn',
    lastName: 'De Wolfe',
    phone: '898-818-6883',
  },
  {
    email: 'fsyfax1m@google.nl',
    password: '8IIcto',
    googleId: '2402220562',
    firstName: 'Franni',
    lastName: 'Syfax',
    phone: '268-278-0498',
  },
  {
    email: 'tbrandenburg1n@independent.co.uk',
    password: 'WcW2I4B',
    googleId: '3770771109',
    firstName: 'Tremaine',
    lastName: 'Brandenburg',
    phone: '536-973-4709',
  },
  {
    email: 'kbetz1o@sitemeter.com',
    password: '0esnYfm2',
    googleId: '8751106639',
    firstName: 'Karena',
    lastName: 'Betz',
    phone: null,
  },
  {
    email: 'hstrettle1p@disqus.com',
    password: 'RldBBzTzz',
    googleId: '7203620093',
    firstName: 'Hube',
    lastName: 'Strettle',
    phone: '219-104-7550',
  },
  {
    email: 'dcasterou1q@umich.edu',
    password: 'bgMbtg',
    googleId: '7724463824',
    firstName: 'Daron',
    lastName: 'Casterou',
    phone: null,
  },
  {
    email: 'smerredy1r@amazon.com',
    password: 'OUps8z',
    googleId: '5127936852',
    firstName: 'Stephine',
    lastName: 'Merredy',
    phone: null,
  },
  {
    email: 'sroebuck1s@xrea.com',
    password: 'vOzjnxJnocO',
    googleId: '5032342513',
    firstName: 'Smith',
    lastName: 'Roebuck',
    phone: '621-670-8260',
  },
  {
    email: 'lthorald1t@google.it',
    password: 'nyKbGxGUat',
    googleId: '0366512706',
    firstName: 'Lindie',
    lastName: 'Thorald',
    phone: '111-169-0081',
  },
  {
    email: 'rblewis1u@bbb.org',
    password: 'MBx9sshyduO',
    googleId: '1212632389',
    firstName: 'Robina',
    lastName: 'Blewis',
    phone: null,
  },
  {
    email: 'kburleigh1v@amazon.co.uk',
    password: '6UV2OIHcW',
    googleId: '5711966146',
    firstName: 'Kinsley',
    lastName: 'Burleigh',
    phone: '249-605-8713',
  },
  {
    email: 'cdoyley1w@archive.org',
    password: 'g9cDhipOL',
    googleId: '8316765039',
    firstName: 'Christabella',
    lastName: 'Doyley',
    phone: null,
  },
  {
    email: 'aepgrave1x@flavors.me',
    password: 'tRn3X0uLvm2',
    googleId: '1177451328',
    firstName: 'Ange',
    lastName: 'Epgrave',
    phone: '850-852-7398',
  },
  {
    email: 'rodogherty1y@t-online.de',
    password: '1dRz7G1qMTF',
    googleId: '0072173629',
    firstName: 'Randell',
    lastName: "O'Dogherty",
    phone: '602-277-3898',
  },
  {
    email: 'mbremen1z@fc2.com',
    password: '67peI6I2',
    googleId: '1428918906',
    firstName: 'Marjorie',
    lastName: 'Bremen',
    phone: '307-949-2206',
  },
  {
    email: 'kkain20@studiopress.com',
    password: 'uLCjo8',
    googleId: '0462266583',
    firstName: 'Kelley',
    lastName: 'Kain',
    phone: null,
  },
  {
    email: 'viglesias21@abc.net.au',
    password: 'YU01T2RZtH',
    googleId: '7882122297',
    firstName: 'Veronika',
    lastName: 'Iglesias',
    phone: null,
  },
  {
    email: 'amcelvine22@disqus.com',
    password: 'NbbKt9wCfRq',
    googleId: '9035696255',
    firstName: 'Alfi',
    lastName: 'McElvine',
    phone: '575-131-0943',
  },
  {
    email: 'dcorkish23@altervista.org',
    password: 'TA9HXR3fPm4',
    googleId: '7886481925',
    firstName: 'Dorelle',
    lastName: 'Corkish',
    phone: '719-209-4828',
  },
  {
    email: 'rboise24@ted.com',
    password: 'woXpZGpgTA',
    googleId: '7143536938',
    firstName: 'Raynor',
    lastName: 'Boise',
    phone: '412-216-9223',
  },
  {
    email: 'aambrosetti25@mtv.com',
    password: '0toohMIo80S0',
    googleId: '9654927470',
    firstName: 'Arman',
    lastName: 'Ambrosetti',
    phone: null,
  },
  {
    email: 'nabelevitz26@eepurl.com',
    password: 'iPXeTH',
    googleId: '5697992149',
    firstName: 'Nat',
    lastName: 'Abelevitz',
    phone: '832-966-2175',
  },
  {
    email: 'ebemwell27@bluehost.com',
    password: 'PIN6uaVY',
    googleId: '1296979865',
    firstName: 'Edan',
    lastName: 'Bemwell',
    phone: null,
  },
  {
    email: 'celeshenar28@g.co',
    password: 'MzCJKGe',
    googleId: '3907647378',
    firstName: 'Cesaro',
    lastName: 'Eleshenar',
    phone: null,
  },
  {
    email: 'sstansbie29@merriam-webster.com',
    password: 'o57wW3ks',
    googleId: '5829594145',
    firstName: 'Sully',
    lastName: 'Stansbie',
    phone: '631-872-4152',
  },
  {
    email: 'unovkovic2a@booking.com',
    password: 'EsFev2',
    googleId: '0881673773',
    firstName: 'Ulrikaumeko',
    lastName: 'Novkovic',
    phone: null,
  },
  {
    email: 'maronson2b@de.vu',
    password: 'nDXyXC',
    googleId: '5958747304',
    firstName: 'Maddie',
    lastName: 'Aronson',
    phone: null,
  },
  {
    email: 'gmattiussi2c@multiply.com',
    password: 'R0ZZ6NkSm1Cv',
    googleId: '3567219383',
    firstName: 'Griswold',
    lastName: 'Mattiussi',
    phone: null,
  },
  {
    email: 'cbromige2d@imdb.com',
    password: 'C5OnGI8Dp',
    googleId: '4148246552',
    firstName: 'Cchaddie',
    lastName: 'Bromige',
    phone: null,
  },
  {
    email: 'wshorland2e@desdev.cn',
    password: '7y433yQ1BMS',
    googleId: '7551916253',
    firstName: 'Wilbert',
    lastName: 'Shorland',
    phone: null,
  },
  {
    email: 'bsilverman2f@yahoo.co.jp',
    password: 'ZNB5YgCIz',
    googleId: '8518436109',
    firstName: 'Birk',
    lastName: 'Silverman',
    phone: '466-810-0151',
  },
  {
    email: 'hiannuzzi2g@list-manage.com',
    password: 'HCFtYcQmQ',
    googleId: '2715593473',
    firstName: 'Heather',
    lastName: 'Iannuzzi',
    phone: '360-627-7117',
  },
  {
    email: 'dclacson2h@msn.com',
    password: '5xfabwA',
    googleId: '7719274849',
    firstName: 'Daryl',
    lastName: 'Clacson',
    phone: null,
  },
  {
    email: 'swiltshear2i@hostgator.com',
    password: 'o9qUWY9gqjZ',
    googleId: '1280682884',
    firstName: 'Stacy',
    lastName: 'Wiltshear',
    phone: null,
  },
  {
    email: 'ifalck2j@xrea.com',
    password: 'MNptqcmhiMVO',
    googleId: '0118979272',
    firstName: 'Ingamar',
    lastName: 'Falck',
    phone: '260-128-0902',
  },
  {
    email: 'mrowley2k@twitpic.com',
    password: 'Z1eEZWapV',
    googleId: '2597968758',
    firstName: 'Minne',
    lastName: 'Rowley',
    phone: '339-146-8302',
  },
  {
    email: 'mgirod2l@tinyurl.com',
    password: 'XusQyyh',
    googleId: '0661452247',
    firstName: 'Michelina',
    lastName: 'Girod',
    phone: '719-894-3197',
  },
  {
    email: 'egannon2m@livejournal.com',
    password: 'hbrIZc',
    googleId: '0179466682',
    firstName: 'Elfie',
    lastName: 'Gannon',
    phone: null,
  },
  {
    email: 'twreakes2n@virginia.edu',
    password: 'GHN6YVV',
    googleId: '3309102424',
    firstName: 'Ty',
    lastName: 'Wreakes',
    phone: null,
  },
  {
    email: 'alutwidge2o@imgur.com',
    password: 'DqRTNBI',
    googleId: '5366455863',
    firstName: 'Amelie',
    lastName: 'Lutwidge',
    phone: '951-787-5186',
  },
  {
    email: 'krainbird2p@google.cn',
    password: 'jp19eK',
    googleId: '7067125235',
    firstName: 'Kalvin',
    lastName: 'Rainbird',
    phone: null,
  },
  {
    email: 'rwindle2q@yale.edu',
    password: 'Igbq41ARCg',
    googleId: '9296660408',
    firstName: 'Richardo',
    lastName: 'Windle',
    phone: '805-864-4943',
  },
  {
    email: 'dslack2r@cafepress.com',
    password: '2RgvcI8lBz',
    googleId: '2519967498',
    firstName: 'Dmitri',
    lastName: 'Slack',
    phone: '138-523-6703',
  },
]

const userSeed = async () => {
  try {
    await Promise.all(
      usersData.map((user) => {
        return User.create(user)
      })
    )
  } catch (err) {
    console.log(err)
  }
}
module.exports = userSeed
